// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: b0aa286dba4ed04c111c1265bdb6a76ba45c22a3d9b9e8dcf36302267d40c51a

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, useEffect, type ReactNode } from "react";

export type ThemeName = "SotaUni";

export const themeNames: ThemeName[] = ["SotaUni"];

export type KcEnvName = never;

export const kcEnvNames: KcEnvName[] = [];

export const kcEnvDefaults: Record<KcEnvName, string> = {};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import("./login/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const defaultLocale = "en";

export const KcLoginPage = lazy(() => import("./login/KcPage"));
export const KcRegisterPage = lazy(() => import("./register/KcPage"));
export const KcResetPasswordPage = lazy(() => import("./reset-password/KcPage"));
export const KcVerifyEmailPage = lazy(() => import("./verify-email/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;

    const localeFromUrl =
        typeof window !== "undefined"
            ? new URLSearchParams(window.location.search).get("locale") ||
              localStorage.getItem("locale")
            : null;

    useEffect(() => {
        if (localeFromUrl) {
            localStorage.setItem("locale", localeFromUrl);
        }
    }, [localeFromUrl]);

    useEffect(() => {
        const handleInput = (e: Event) => {
            const target = e.target as HTMLInputElement | HTMLTextAreaElement;
            if (
                !target ||
                ![
                    "username",
                    "password",
                    "email",
                    "firstName",
                    "lastName",
                    "password-confirm",
                    "password-new"
                ].includes(target.name)
            )
                return;

            const emojiRegex = /\p{Extended_Pictographic}/gu;
            if (emojiRegex.test(target.value)) {
                target.value = target.value.replace(emojiRegex, "");
            }
        };

        document.addEventListener("input", handleInput, true);
        return () => document.removeEventListener("input", handleInput, true);
    }, []);

    useEffect(() => {
        const handleBlur = (e: Event) => {
            const target = e.target as HTMLInputElement | HTMLTextAreaElement;
            if (
                !target ||
                !["username", "email", "firstName", "lastName"].includes(target.name)
            )
                return;

            const value = target.value;
            const trimmedValue = value.trim();
            if (value !== trimmedValue) {
                const setter = Object.getOwnPropertyDescriptor(
                    window.HTMLInputElement.prototype,
                    "value"
                )?.set;
                if (setter) {
                    setter.call(target, trimmedValue);
                } else {
                    target.value = trimmedValue;
                }
                target.dispatchEvent(new Event("input", { bubbles: true }));
            }
        };

        document.addEventListener("blur", handleBlur, true);

        return () => {
            document.removeEventListener("blur", handleBlur, true);
        };
    }, []);

    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        if (kcContext.pageId === "register.ftl") {
                            return <KcRegisterPage kcContext={kcContext} />;
                        }
                        if (kcContext.pageId === "login-reset-password.ftl") {
                            return <KcResetPasswordPage kcContext={kcContext} />;
                        }
                        if (kcContext.pageId === "login-verify-email.ftl") {
                            return <KcVerifyEmailPage kcContext={kcContext} />;
                        }
                        return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL;

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from "@storybook/react-vite";
